### ISSUE TITLE
Missing tab in Call Search

### ISSUE THREAD

**Issue by dppancake** [sipcapture/hepsub-apiban#2]
Hi,

I've deployed this hepsub in a docker container with docker-compose. It succesfully connects ` message: 'successfully created agent record'` to homer, but the tab missing in the dialog (should be next to Loki). Maybe I have to change some mappings?

I'm running the latest version of the Homer-webapp and Hepsub-apiban.

Thanks in advance.

**Comment by lmangani** [comment]
Hi @Robbin1998 that's correct, you need to create an `ip` type feeding back the IPs. Somehow I forgot to add it to the documentation, I'll try to do so whenever possible.

**Comment by lmangani** [comment]
Could you try switch the APIBAN config to use the `cdr` type instead of `ip`? I think this is the typo in the example as the `cdr` type does return a source_ip by default which is required for the lookups

**Comment by dppancake** [comment]
That worked. The tab is now showing and also contains all the information. Thanks for the help!

**Comment by lmangani** [comment]
Thanks for the report! fixed the example `config.js` accordingly. Let us know if you have any suggestions!
